name: C/C++ CI

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: Compile
      working-directory: build
      run: make -j2
    - name: Test
      working-directory: build
      run: ctest -j2
