name: Ubuntu OpenMP

on:
  push:
    branches: [ubuntu, static]
  pull_request:
    branches: [ubuntu, static]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir -p build
        cd build
        cmake -DUSE_OPENMP=ON ..
    - name: Compile
      working-directory: build
      run: make -j2
    - name: Test
      working-directory: build
      run: ctest -j2
