name: Ubuntu and Mac OpenMP

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir -p build
        cd build
        cmake -DUSE_OPENMP=ON ..
    - name: Compile
      working-directory: build
      run: make -j2
    - name: Test
      working-directory: build
      run: ctest -j2
